[git_status]
ahead = ">"
behind = "<"
deleted = "x"
diverged = "/"
renamed = "^"

[golang]
symbol = "ğŸ’¨ "

[nodejs]
symbol = "ğŸ“¦ "

[package]
disabled = true

[directory]
truncation_length = 8

[hostname]
disabled = true

[username]
disabled = true

[kubernetes]
disabled = false
symbol = "ğŸ’€ "
style = "bold white"
[kubernetes.context_aliases]
"kind-kind" = "kind"
"validator-control-plane" = "stg"
"jessemillar-provision-test" = "dev"

[rust]
symbol = "ğŸš "

[env_var]
variable = "PROMPT_FINDER_CHARACTER"
default = "ğŸ”¥"
