[git_status]
deleted = "x"

[golang]
symbol = "ðŸ’¨ "

[nodejs]
symbol = "ðŸ“¦ "

[package]
symbol = ""

[directory]
truncation_length = 8

[hostname]
style = "bold green"
disabled = true

[username]
show_always = true

[memory_usage]
disabled = false
show_percentage = true
style = "bold white"
threshold = 50
